### ISSUE TITLE
What is the matter in deployment. 

### ISSUE THREAD

**Issue by iashyam** [henryleach/grey-book#2]
@henryleach Sir, I used your theme [grey-book](https://github.com/henryleach/grey-book) to build my website. It was working fine offline with the Hugo server, but when I deployed it in GitHub pages, i was not getting the same website. I used this tutorial from the official Hugo website for [deployment](https://gohugo.io/hosting-and-deployment/hosting-on-github/). Can you please help identify the issue since you have not posted anything particular about a deployment in your GitHub repo. I would really appreciate it. 

You can find the website here ![The Rest Frame](https://iashyam.github.io/blog/)

![image](https://github.com/henryleach/grey-book/assets/70376025/aa23bc9c-c8a0-4201-9463-864b5651c1e0)

**Comment by henryleach** [comment]
Hello @iashyam . I've never used GitHub Actions, so can't really comment on how to use them. 

From the screenshot above it looks like the CSS isn't being loaded, but the content is. The only things I can think of try are:
* Build the site locally (__not__ using the Hugo server) and see what the resulting pages look like in a browser in the `/public` folder (which is what I assume GitHub would see).
* Check how you're importing the theme. If it's via a [Git Submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) then your checkout of the repository needs the `--recurse-submodules` option, otherwise it won't actually fetch the code of the theme submodule, but just an empty directory.

PS. Your last link gives me only an error message: `Non-Image content-type returned`.

**Comment by iashyam** [comment]
The `index.html` file in the' public' folder looks terrible. I tried cloning the repo in the themes folder, and it also doesn't work. There is some problem that I don't know of, I am sorry.

**Comment by iashyam** [comment]
@henryleach Okay, I have not hosted the website on Netlify. It is working fine, but I am very disappointed to see the math support. It is not supporting latex-markdown. Have I done anything wrong?

[Find the website here](https://iashyamblog.netlify.app)

**Comment by iashyam** [comment]
Okay! I have solved the math problem. But I find it when I use it from the phone that your theme is not responsive. You can see it on your website, too. The code snippets goes out of the phone when you use it from the phone. I would really appreciate if you can make the website responsive.

**Comment by henryleach** [comment]
Hello, this 'issue' appears to have become a random Q&A and feature request thread - not really an issue that can be solved

This theme is the one I use for my own purposes on my own site, one which doesn't contain currently contain any maths or long lines of code. As such I'm not taking feature requests. 

If you want to change the theme: adding MathsJax support, make it more responsive or able to with long code lines some other way - feel free to fork it and adapt it to your own needs. It's licensed in such a way you can do so without restriction.

**Comment by iashyam** [comment]
Sir
If I make any change in `static/css/style.css` they will reflect for once but they disappear when I switch pages or refresh why?
